/**
 * Shared primitive unions and scale helpers used across every model.
 *
 * Rating scale convention for the whole game: 1-99 integers.
 *   1-29 raw beginner | 30-49 club | 50-64 state | 65-79 first-class
 *   80-89 international | 90-99 all-time great
 */

/** Integer 1-99. Not enforced by the compiler; enforced by `clampRating`. */
export type Rating = number;

/** Integer 0-100, used for percentages such as fitness and morale. */
export type Percent = number;

export const RATING_MIN = 1;
export const RATING_MAX = 99;

export function clampRating(value: number): Rating {
  return Math.max(RATING_MIN, Math.min(RATING_MAX, Math.round(value)));
}

export function clampPercent(value: number): Percent {
  return Math.max(0, Math.min(100, Math.round(value)));
}

/** ISO-8601 date string, `YYYY-MM-DD`. The career clock runs on in-game dates. */
export type ISODate = string;

/** Unique identifier. Generated by `newId` in `src/engine/id.ts`. */
export type Id = string;

export type MatchFormat = 'T20' | 'ODI' | 'ONE_DAY' | 'MULTI_DAY' | 'TEST';

/** Number of overs per innings, or `null` for unlimited-overs (multi-day) cricket. */
export const OVERS_BY_FORMAT: Record<MatchFormat, number | null> = {
  T20: 20,
  ODI: 50,
  ONE_DAY: 50,
  MULTI_DAY: null,
  TEST: null,
};

export type MatchPhase =
  | 'POWERPLAY'
  | 'MIDDLE'
  | 'DEATH'
  | 'NEW_BALL'
  | 'OLD_BALL'
  | 'SECOND_NEW_BALL';

export type Hand = 'RIGHT' | 'LEFT';

export type BattingStyle = 'RIGHT_HAND_BAT' | 'LEFT_HAND_BAT';

export type BowlingStyle =
  | 'RIGHT_ARM_FAST'
  | 'RIGHT_ARM_FAST_MEDIUM'
  | 'RIGHT_ARM_MEDIUM'
  | 'LEFT_ARM_FAST'
  | 'LEFT_ARM_FAST_MEDIUM'
  | 'LEFT_ARM_MEDIUM'
  | 'OFF_SPIN'
  | 'LEG_SPIN'
  | 'LEFT_ARM_ORTHODOX'
  | 'LEFT_ARM_WRIST_SPIN'
  | 'NONE';

export type PlayerRole =
  | 'BATTER'
  | 'OPENING_BATTER'
  | 'WICKET_KEEPER_BATTER'
  | 'BATTING_ALLROUNDER'
  | 'BOWLING_ALLROUNDER'
  | 'PACE_BOWLER'
  | 'SPIN_BOWLER';

/** Level a team or competition sits at. Drives opponent strength and scouting. */
export type CompetitionLevel =
  | 'SCHOOL'
  | 'CLUB'
  | 'DISTRICT'
  | 'STATE_AGE_GROUP'
  | 'STATE_SENIOR'
  | 'ZONAL'
  | 'NATIONAL_A'
  | 'FRANCHISE'
  | 'INTERNATIONAL';

export type TeamRole = 'PLAYER' | 'VICE_CAPTAIN' | 'CAPTAIN';
